//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.20 at 11:37:30 PM CEST 
//


package org.firma.client.oxm.proverastanja;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ws.banka.org/ws/schema/proveraStanja}brojRacuna"/>
 *         &lt;element ref="{http://ws.banka.org/ws/schema/proveraStanja}naziv"/>
 *         &lt;element ref="{http://ws.banka.org/ws/schema/proveraStanja}status"/>
 *         &lt;element ref="{http://ws.banka.org/ws/schema/proveraStanja}trenutnoStanje"/>
 *         &lt;element ref="{http://ws.banka.org/ws/schema/proveraStanja}rezervisanaSredstva"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"brojRacuna",
		"naziv",
		"status",
		"trenutnoStanje",
		"rezervisanaSredstva"
})
@XmlRootElement(name = "proveraStanjaResponse")
public class ProveraStanjaResponse {

	@XmlElement(required = true)
	protected String brojRacuna;
	@XmlElement(required = true)
	protected String naziv;
	@XmlElement(required = true)
	protected String status;
	protected double trenutnoStanje;
	protected double rezervisanaSredstva;

	/**
	 * Gets the value of the brojRacuna property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getBrojRacuna() {
		return brojRacuna;
	}

	/**
	 * Sets the value of the brojRacuna property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setBrojRacuna(String value) {
		this.brojRacuna = value;
	}

	/**
	 * Gets the value of the naziv property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getNaziv() {
		return naziv;
	}

	/**
	 * Sets the value of the naziv property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setNaziv(String value) {
		this.naziv = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setStatus(String value) {
		this.status = value;
	}

	/**
	 * Gets the value of the trenutnoStanje property.
	 * 
	 */
	public double getTrenutnoStanje() {
		return trenutnoStanje;
	}

	/**
	 * Sets the value of the trenutnoStanje property.
	 * 
	 */
	public void setTrenutnoStanje(double value) {
		this.trenutnoStanje = value;
	}

	/**
	 * Gets the value of the rezervisanaSredstva property.
	 * 
	 */
	public double getRezervisanaSredstva() {
		return rezervisanaSredstva;
	}

	/**
	 * Sets the value of the rezervisanaSredstva property.
	 * 
	 */
	public void setRezervisanaSredstva(double value) {
		this.rezervisanaSredstva = value;
	}

}
