//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.20 at 11:37:30 PM CEST 
//


package org.banka.ws.ws.schema.proverastanja;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.banka.ws.ws.schema.proverastanja package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Naziv_QNAME = new QName("http://ws.banka.org/ws/schema/proveraStanja", "naziv");
    private final static QName _RezervisanaSredstva_QNAME = new QName("http://ws.banka.org/ws/schema/proveraStanja", "rezervisanaSredstva");
    private final static QName _Status_QNAME = new QName("http://ws.banka.org/ws/schema/proveraStanja", "status");
    private final static QName _TrenutnoStanje_QNAME = new QName("http://ws.banka.org/ws/schema/proveraStanja", "trenutnoStanje");
    private final static QName _BrojRacuna_QNAME = new QName("http://ws.banka.org/ws/schema/proveraStanja", "brojRacuna");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.banka.ws.ws.schema.proverastanja
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProveraStanjaRequest }
     * 
     */
    public ProveraStanjaRequest createProveraStanjaRequest() {
        return new ProveraStanjaRequest();
    }

    /**
     * Create an instance of {@link ProveraStanjaResponse }
     * 
     */
    public ProveraStanjaResponse createProveraStanjaResponse() {
        return new ProveraStanjaResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/proveraStanja", name = "naziv")
    public JAXBElement<String> createNaziv(String value) {
        return new JAXBElement<String>(_Naziv_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/proveraStanja", name = "rezervisanaSredstva")
    public JAXBElement<Double> createRezervisanaSredstva(Double value) {
        return new JAXBElement<Double>(_RezervisanaSredstva_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/proveraStanja", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/proveraStanja", name = "trenutnoStanje")
    public JAXBElement<Double> createTrenutnoStanje(Double value) {
        return new JAXBElement<Double>(_TrenutnoStanje_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/proveraStanja", name = "brojRacuna")
    public JAXBElement<String> createBrojRacuna(String value) {
        return new JAXBElement<String>(_BrojRacuna_QNAME, String.class, null, value);
    }

}
