//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.20 at 11:36:45 PM CEST 
//


package org.banka.ws.ws.schema.nalogzaplacanje;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.banka.ws.ws.schema.nalogzaplacanje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Opis_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "opis");
    private final static QName _OznakaValute_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "oznakaValute");
    private final static QName _ID_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "ID");
    private final static QName _Primalac_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "primalac");
    private final static QName _RacunPoverioca_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "racunPoverioca");
    private final static QName _RacunDuznika_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "racunDuznika");
    private final static QName _Hitno_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "hitno");
    private final static QName _SvrhaPlacanja_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "svrhaPlacanja");
    private final static QName _Duznik_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "duznik");
    private final static QName _DatumValute_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "datumValute");
    private final static QName _ModelOdobrenja_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "modelOdobrenja");
    private final static QName _DatumNaloga_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "datumNaloga");
    private final static QName _Iznos_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "iznos");
    private final static QName _PozivNaBrojOdobrenja_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "pozivNaBrojOdobrenja");
    private final static QName _Status_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "status");
    private final static QName _ModelZaduzenja_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "modelZaduzenja");
    private final static QName _PozivNaBrojZaduzenja_QNAME = new QName("http://ws.banka.org/ws/schema/nalogZaPlacanje", "pozivNaBrojZaduzenja");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.banka.ws.ws.schema.nalogzaplacanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NalogZaPlacanjeResponse }
     * 
     */
    public NalogZaPlacanjeResponse createNalogZaPlacanjeResponse() {
        return new NalogZaPlacanjeResponse();
    }

    /**
     * Create an instance of {@link NalogZaPlacanjeRequest }
     * 
     */
    public NalogZaPlacanjeRequest createNalogZaPlacanjeRequest() {
        return new NalogZaPlacanjeRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "opis")
    public JAXBElement<String> createOpis(String value) {
        return new JAXBElement<String>(_Opis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "oznakaValute")
    public JAXBElement<String> createOznakaValute(String value) {
        return new JAXBElement<String>(_OznakaValute_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "ID")
    public JAXBElement<String> createID(String value) {
        return new JAXBElement<String>(_ID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "primalac")
    public JAXBElement<String> createPrimalac(String value) {
        return new JAXBElement<String>(_Primalac_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "racunPoverioca")
    public JAXBElement<String> createRacunPoverioca(String value) {
        return new JAXBElement<String>(_RacunPoverioca_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "racunDuznika")
    public JAXBElement<String> createRacunDuznika(String value) {
        return new JAXBElement<String>(_RacunDuznika_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "hitno")
    public JAXBElement<Boolean> createHitno(Boolean value) {
        return new JAXBElement<Boolean>(_Hitno_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "svrhaPlacanja")
    public JAXBElement<String> createSvrhaPlacanja(String value) {
        return new JAXBElement<String>(_SvrhaPlacanja_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "duznik")
    public JAXBElement<String> createDuznik(String value) {
        return new JAXBElement<String>(_Duznik_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "datumValute")
    public JAXBElement<XMLGregorianCalendar> createDatumValute(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumValute_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "modelOdobrenja")
    public JAXBElement<BigInteger> createModelOdobrenja(BigInteger value) {
        return new JAXBElement<BigInteger>(_ModelOdobrenja_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "datumNaloga")
    public JAXBElement<XMLGregorianCalendar> createDatumNaloga(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumNaloga_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "iznos")
    public JAXBElement<Double> createIznos(Double value) {
        return new JAXBElement<Double>(_Iznos_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "pozivNaBrojOdobrenja")
    public JAXBElement<String> createPozivNaBrojOdobrenja(String value) {
        return new JAXBElement<String>(_PozivNaBrojOdobrenja_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "modelZaduzenja")
    public JAXBElement<BigInteger> createModelZaduzenja(BigInteger value) {
        return new JAXBElement<BigInteger>(_ModelZaduzenja_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.banka.org/ws/schema/nalogZaPlacanje", name = "pozivNaBrojZaduzenja")
    public JAXBElement<String> createPozivNaBrojZaduzenja(String value) {
        return new JAXBElement<String>(_PozivNaBrojZaduzenja_QNAME, String.class, null, value);
    }

}
